// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package larpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientContract struct {
	Uuid                 string       `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Asset                string       `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               float64      `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	AmountSatMargin      int64        `protobuf:"varint,5,opt,name=amount_sat_margin,json=amountSatMargin,proto3" json:"amount_sat_margin,omitempty"`
	AmountSatInit        int64        `protobuf:"varint,6,opt,name=amount_sat_init,json=amountSatInit,proto3" json:"amount_sat_init,omitempty"`
	MarginInvoice        string       `protobuf:"bytes,7,opt,name=margin_invoice,json=marginInvoice,proto3" json:"margin_invoice,omitempty"`
	InitInvoice          string       `protobuf:"bytes,8,opt,name=init_invoice,json=initInvoice,proto3" json:"init_invoice,omitempty"`
	ContractType         ContractType `protobuf:"varint,9,opt,name=contract_type,json=contractType,proto3,enum=ladrpc.ContractType" json:"contract_type,omitempty"`
	InvoicesPaid         bool         `protobuf:"varint,10,opt,name=invoices_paid,json=invoicesPaid,proto3" json:"invoices_paid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientContract) Reset()         { *m = ClientContract{} }
func (m *ClientContract) String() string { return proto.CompactTextString(m) }
func (*ClientContract) ProtoMessage()    {}
func (*ClientContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *ClientContract) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientContract.Unmarshal(m, b)
}
func (m *ClientContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientContract.Marshal(b, m, deterministic)
}
func (m *ClientContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientContract.Merge(m, src)
}
func (m *ClientContract) XXX_Size() int {
	return xxx_messageInfo_ClientContract.Size(m)
}
func (m *ClientContract) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientContract.DiscardUnknown(m)
}

var xxx_messageInfo_ClientContract proto.InternalMessageInfo

func (m *ClientContract) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ClientContract) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ClientContract) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ClientContract) GetAmountSatMargin() int64 {
	if m != nil {
		return m.AmountSatMargin
	}
	return 0
}

func (m *ClientContract) GetAmountSatInit() int64 {
	if m != nil {
		return m.AmountSatInit
	}
	return 0
}

func (m *ClientContract) GetMarginInvoice() string {
	if m != nil {
		return m.MarginInvoice
	}
	return ""
}

func (m *ClientContract) GetInitInvoice() string {
	if m != nil {
		return m.InitInvoice
	}
	return ""
}

func (m *ClientContract) GetContractType() ContractType {
	if m != nil {
		return m.ContractType
	}
	return ContractType_FUNDED
}

func (m *ClientContract) GetInvoicesPaid() bool {
	if m != nil {
		return m.InvoicesPaid
	}
	return false
}

type ClientCreateContractRequest struct {
	Asset                string       `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               float64      `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	ContractType         ContractType `protobuf:"varint,3,opt,name=contract_type,json=contractType,proto3,enum=ladrpc.ContractType" json:"contract_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ClientCreateContractRequest) Reset()         { *m = ClientCreateContractRequest{} }
func (m *ClientCreateContractRequest) String() string { return proto.CompactTextString(m) }
func (*ClientCreateContractRequest) ProtoMessage()    {}
func (*ClientCreateContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *ClientCreateContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCreateContractRequest.Unmarshal(m, b)
}
func (m *ClientCreateContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCreateContractRequest.Marshal(b, m, deterministic)
}
func (m *ClientCreateContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCreateContractRequest.Merge(m, src)
}
func (m *ClientCreateContractRequest) XXX_Size() int {
	return xxx_messageInfo_ClientCreateContractRequest.Size(m)
}
func (m *ClientCreateContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCreateContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCreateContractRequest proto.InternalMessageInfo

func (m *ClientCreateContractRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *ClientCreateContractRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *ClientCreateContractRequest) GetContractType() ContractType {
	if m != nil {
		return m.ContractType
	}
	return ContractType_FUNDED
}

type ClientCreateContractResponse struct {
	Contract             *ClientContract `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	ExpectedMarginAmount int64           `protobuf:"varint,2,opt,name=expected_margin_amount,json=expectedMarginAmount,proto3" json:"expected_margin_amount,omitempty"`
	ExpectedInitAmount   int64           `protobuf:"varint,3,opt,name=expected_init_amount,json=expectedInitAmount,proto3" json:"expected_init_amount,omitempty"`
	OurPrice             float64         `protobuf:"fixed64,4,opt,name=our_price,json=ourPrice,proto3" json:"our_price,omitempty"`
	ServerPrice          float64         `protobuf:"fixed64,5,opt,name=server_price,json=serverPrice,proto3" json:"server_price,omitempty"`
	PercentMargin        float64         `protobuf:"fixed64,6,opt,name=percent_margin,json=percentMargin,proto3" json:"percent_margin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientCreateContractResponse) Reset()         { *m = ClientCreateContractResponse{} }
func (m *ClientCreateContractResponse) String() string { return proto.CompactTextString(m) }
func (*ClientCreateContractResponse) ProtoMessage()    {}
func (*ClientCreateContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *ClientCreateContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCreateContractResponse.Unmarshal(m, b)
}
func (m *ClientCreateContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCreateContractResponse.Marshal(b, m, deterministic)
}
func (m *ClientCreateContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCreateContractResponse.Merge(m, src)
}
func (m *ClientCreateContractResponse) XXX_Size() int {
	return xxx_messageInfo_ClientCreateContractResponse.Size(m)
}
func (m *ClientCreateContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCreateContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCreateContractResponse proto.InternalMessageInfo

func (m *ClientCreateContractResponse) GetContract() *ClientContract {
	if m != nil {
		return m.Contract
	}
	return nil
}

func (m *ClientCreateContractResponse) GetExpectedMarginAmount() int64 {
	if m != nil {
		return m.ExpectedMarginAmount
	}
	return 0
}

func (m *ClientCreateContractResponse) GetExpectedInitAmount() int64 {
	if m != nil {
		return m.ExpectedInitAmount
	}
	return 0
}

func (m *ClientCreateContractResponse) GetOurPrice() float64 {
	if m != nil {
		return m.OurPrice
	}
	return 0
}

func (m *ClientCreateContractResponse) GetServerPrice() float64 {
	if m != nil {
		return m.ServerPrice
	}
	return 0
}

func (m *ClientCreateContractResponse) GetPercentMargin() float64 {
	if m != nil {
		return m.PercentMargin
	}
	return 0
}

type ClientOpenContractRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientOpenContractRequest) Reset()         { *m = ClientOpenContractRequest{} }
func (m *ClientOpenContractRequest) String() string { return proto.CompactTextString(m) }
func (*ClientOpenContractRequest) ProtoMessage()    {}
func (*ClientOpenContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *ClientOpenContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientOpenContractRequest.Unmarshal(m, b)
}
func (m *ClientOpenContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientOpenContractRequest.Marshal(b, m, deterministic)
}
func (m *ClientOpenContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientOpenContractRequest.Merge(m, src)
}
func (m *ClientOpenContractRequest) XXX_Size() int {
	return xxx_messageInfo_ClientOpenContractRequest.Size(m)
}
func (m *ClientOpenContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientOpenContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientOpenContractRequest proto.InternalMessageInfo

func (m *ClientOpenContractRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ClientOpenContractResponse struct {
	Contract             *ClientContract `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ClientOpenContractResponse) Reset()         { *m = ClientOpenContractResponse{} }
func (m *ClientOpenContractResponse) String() string { return proto.CompactTextString(m) }
func (*ClientOpenContractResponse) ProtoMessage()    {}
func (*ClientOpenContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *ClientOpenContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientOpenContractResponse.Unmarshal(m, b)
}
func (m *ClientOpenContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientOpenContractResponse.Marshal(b, m, deterministic)
}
func (m *ClientOpenContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientOpenContractResponse.Merge(m, src)
}
func (m *ClientOpenContractResponse) XXX_Size() int {
	return xxx_messageInfo_ClientOpenContractResponse.Size(m)
}
func (m *ClientOpenContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientOpenContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientOpenContractResponse proto.InternalMessageInfo

func (m *ClientOpenContractResponse) GetContract() *ClientContract {
	if m != nil {
		return m.Contract
	}
	return nil
}

type ClientCloseContractRequest struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientCloseContractRequest) Reset()         { *m = ClientCloseContractRequest{} }
func (m *ClientCloseContractRequest) String() string { return proto.CompactTextString(m) }
func (*ClientCloseContractRequest) ProtoMessage()    {}
func (*ClientCloseContractRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{5}
}

func (m *ClientCloseContractRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCloseContractRequest.Unmarshal(m, b)
}
func (m *ClientCloseContractRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCloseContractRequest.Marshal(b, m, deterministic)
}
func (m *ClientCloseContractRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCloseContractRequest.Merge(m, src)
}
func (m *ClientCloseContractRequest) XXX_Size() int {
	return xxx_messageInfo_ClientCloseContractRequest.Size(m)
}
func (m *ClientCloseContractRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCloseContractRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCloseContractRequest proto.InternalMessageInfo

func (m *ClientCloseContractRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type ClientCloseContractResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientCloseContractResponse) Reset()         { *m = ClientCloseContractResponse{} }
func (m *ClientCloseContractResponse) String() string { return proto.CompactTextString(m) }
func (*ClientCloseContractResponse) ProtoMessage()    {}
func (*ClientCloseContractResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{6}
}

func (m *ClientCloseContractResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientCloseContractResponse.Unmarshal(m, b)
}
func (m *ClientCloseContractResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientCloseContractResponse.Marshal(b, m, deterministic)
}
func (m *ClientCloseContractResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientCloseContractResponse.Merge(m, src)
}
func (m *ClientCloseContractResponse) XXX_Size() int {
	return xxx_messageInfo_ClientCloseContractResponse.Size(m)
}
func (m *ClientCloseContractResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientCloseContractResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientCloseContractResponse proto.InternalMessageInfo

type ClientListContractsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientListContractsRequest) Reset()         { *m = ClientListContractsRequest{} }
func (m *ClientListContractsRequest) String() string { return proto.CompactTextString(m) }
func (*ClientListContractsRequest) ProtoMessage()    {}
func (*ClientListContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{7}
}

func (m *ClientListContractsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientListContractsRequest.Unmarshal(m, b)
}
func (m *ClientListContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientListContractsRequest.Marshal(b, m, deterministic)
}
func (m *ClientListContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientListContractsRequest.Merge(m, src)
}
func (m *ClientListContractsRequest) XXX_Size() int {
	return xxx_messageInfo_ClientListContractsRequest.Size(m)
}
func (m *ClientListContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientListContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientListContractsRequest proto.InternalMessageInfo

type ClientListContractsResponse struct {
	Contracts            []*ClientContract `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClientListContractsResponse) Reset()         { *m = ClientListContractsResponse{} }
func (m *ClientListContractsResponse) String() string { return proto.CompactTextString(m) }
func (*ClientListContractsResponse) ProtoMessage()    {}
func (*ClientListContractsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{8}
}

func (m *ClientListContractsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientListContractsResponse.Unmarshal(m, b)
}
func (m *ClientListContractsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientListContractsResponse.Marshal(b, m, deterministic)
}
func (m *ClientListContractsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientListContractsResponse.Merge(m, src)
}
func (m *ClientListContractsResponse) XXX_Size() int {
	return xxx_messageInfo_ClientListContractsResponse.Size(m)
}
func (m *ClientListContractsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientListContractsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientListContractsResponse proto.InternalMessageInfo

func (m *ClientListContractsResponse) GetContracts() []*ClientContract {
	if m != nil {
		return m.Contracts
	}
	return nil
}

type ClientRequestPaymentRequestRequest struct {
	AmountSat            int64    `protobuf:"varint,1,opt,name=amount_sat,json=amountSat,proto3" json:"amount_sat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestPaymentRequestRequest) Reset()         { *m = ClientRequestPaymentRequestRequest{} }
func (m *ClientRequestPaymentRequestRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequestPaymentRequestRequest) ProtoMessage()    {}
func (*ClientRequestPaymentRequestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{9}
}

func (m *ClientRequestPaymentRequestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestPaymentRequestRequest.Unmarshal(m, b)
}
func (m *ClientRequestPaymentRequestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestPaymentRequestRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequestPaymentRequestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestPaymentRequestRequest.Merge(m, src)
}
func (m *ClientRequestPaymentRequestRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequestPaymentRequestRequest.Size(m)
}
func (m *ClientRequestPaymentRequestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestPaymentRequestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestPaymentRequestRequest proto.InternalMessageInfo

func (m *ClientRequestPaymentRequestRequest) GetAmountSat() int64 {
	if m != nil {
		return m.AmountSat
	}
	return 0
}

type ClientRequestPaymentRequestResponse struct {
	PayReq               string   `protobuf:"bytes,1,opt,name=pay_req,json=payReq,proto3" json:"pay_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestPaymentRequestResponse) Reset()         { *m = ClientRequestPaymentRequestResponse{} }
func (m *ClientRequestPaymentRequestResponse) String() string { return proto.CompactTextString(m) }
func (*ClientRequestPaymentRequestResponse) ProtoMessage()    {}
func (*ClientRequestPaymentRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{10}
}

func (m *ClientRequestPaymentRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestPaymentRequestResponse.Unmarshal(m, b)
}
func (m *ClientRequestPaymentRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestPaymentRequestResponse.Marshal(b, m, deterministic)
}
func (m *ClientRequestPaymentRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestPaymentRequestResponse.Merge(m, src)
}
func (m *ClientRequestPaymentRequestResponse) XXX_Size() int {
	return xxx_messageInfo_ClientRequestPaymentRequestResponse.Size(m)
}
func (m *ClientRequestPaymentRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestPaymentRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestPaymentRequestResponse proto.InternalMessageInfo

func (m *ClientRequestPaymentRequestResponse) GetPayReq() string {
	if m != nil {
		return m.PayReq
	}
	return ""
}

type ClientRequestPaymentRequest struct {
	PayReq               string   `protobuf:"bytes,1,opt,name=pay_req,json=payReq,proto3" json:"pay_req,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestPaymentRequest) Reset()         { *m = ClientRequestPaymentRequest{} }
func (m *ClientRequestPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*ClientRequestPaymentRequest) ProtoMessage()    {}
func (*ClientRequestPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{11}
}

func (m *ClientRequestPaymentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestPaymentRequest.Unmarshal(m, b)
}
func (m *ClientRequestPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestPaymentRequest.Marshal(b, m, deterministic)
}
func (m *ClientRequestPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestPaymentRequest.Merge(m, src)
}
func (m *ClientRequestPaymentRequest) XXX_Size() int {
	return xxx_messageInfo_ClientRequestPaymentRequest.Size(m)
}
func (m *ClientRequestPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestPaymentRequest proto.InternalMessageInfo

func (m *ClientRequestPaymentRequest) GetPayReq() string {
	if m != nil {
		return m.PayReq
	}
	return ""
}

type ClientRequestPaymentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientRequestPaymentResponse) Reset()         { *m = ClientRequestPaymentResponse{} }
func (m *ClientRequestPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*ClientRequestPaymentResponse) ProtoMessage()    {}
func (*ClientRequestPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{12}
}

func (m *ClientRequestPaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientRequestPaymentResponse.Unmarshal(m, b)
}
func (m *ClientRequestPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientRequestPaymentResponse.Marshal(b, m, deterministic)
}
func (m *ClientRequestPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientRequestPaymentResponse.Merge(m, src)
}
func (m *ClientRequestPaymentResponse) XXX_Size() int {
	return xxx_messageInfo_ClientRequestPaymentResponse.Size(m)
}
func (m *ClientRequestPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientRequestPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientRequestPaymentResponse proto.InternalMessageInfo

type ClientSubscribeContractsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSubscribeContractsRequest) Reset()         { *m = ClientSubscribeContractsRequest{} }
func (m *ClientSubscribeContractsRequest) String() string { return proto.CompactTextString(m) }
func (*ClientSubscribeContractsRequest) ProtoMessage()    {}
func (*ClientSubscribeContractsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{13}
}

func (m *ClientSubscribeContractsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSubscribeContractsRequest.Unmarshal(m, b)
}
func (m *ClientSubscribeContractsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSubscribeContractsRequest.Marshal(b, m, deterministic)
}
func (m *ClientSubscribeContractsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSubscribeContractsRequest.Merge(m, src)
}
func (m *ClientSubscribeContractsRequest) XXX_Size() int {
	return xxx_messageInfo_ClientSubscribeContractsRequest.Size(m)
}
func (m *ClientSubscribeContractsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSubscribeContractsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSubscribeContractsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ClientContract)(nil), "larpc.ClientContract")
	proto.RegisterType((*ClientCreateContractRequest)(nil), "larpc.ClientCreateContractRequest")
	proto.RegisterType((*ClientCreateContractResponse)(nil), "larpc.ClientCreateContractResponse")
	proto.RegisterType((*ClientOpenContractRequest)(nil), "larpc.ClientOpenContractRequest")
	proto.RegisterType((*ClientOpenContractResponse)(nil), "larpc.ClientOpenContractResponse")
	proto.RegisterType((*ClientCloseContractRequest)(nil), "larpc.ClientCloseContractRequest")
	proto.RegisterType((*ClientCloseContractResponse)(nil), "larpc.ClientCloseContractResponse")
	proto.RegisterType((*ClientListContractsRequest)(nil), "larpc.ClientListContractsRequest")
	proto.RegisterType((*ClientListContractsResponse)(nil), "larpc.ClientListContractsResponse")
	proto.RegisterType((*ClientRequestPaymentRequestRequest)(nil), "larpc.ClientRequestPaymentRequestRequest")
	proto.RegisterType((*ClientRequestPaymentRequestResponse)(nil), "larpc.ClientRequestPaymentRequestResponse")
	proto.RegisterType((*ClientRequestPaymentRequest)(nil), "larpc.ClientRequestPaymentRequest")
	proto.RegisterType((*ClientRequestPaymentResponse)(nil), "larpc.ClientRequestPaymentResponse")
	proto.RegisterType((*ClientSubscribeContractsRequest)(nil), "larpc.ClientSubscribeContractsRequest")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 785 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x4e, 0x13, 0x41,
	0x14, 0xce, 0xb6, 0xb4, 0xb4, 0xa7, 0x3f, 0xe8, 0x84, 0x9f, 0x75, 0x29, 0x5a, 0x06, 0x21, 0x95,
	0xc4, 0x16, 0xc1, 0x98, 0xe8, 0x85, 0x09, 0xf6, 0x8a, 0x44, 0x03, 0x59, 0x0c, 0x89, 0x7a, 0xb1,
	0x19, 0xb6, 0x13, 0xb2, 0x49, 0xd9, 0x1d, 0x66, 0xa6, 0xc4, 0xde, 0x7a, 0xe1, 0x03, 0xe8, 0x0b,
	0xf8, 0x48, 0x26, 0x5e, 0xf8, 0x02, 0x3e, 0x88, 0xe9, 0xcc, 0xec, 0xb6, 0xbb, 0x6e, 0x1b, 0xe2,
	0x5d, 0xe7, 0x9c, 0xef, 0xfc, 0x7d, 0xe7, 0x3b, 0xb0, 0x50, 0xf7, 0x87, 0x01, 0x0d, 0x65, 0x97,
	0xf1, 0x48, 0x46, 0xa8, 0x34, 0x24, 0x9c, 0xf9, 0x4e, 0x5d, 0x50, 0x7e, 0x4b, 0xb9, 0x36, 0x3a,
	0xad, 0xab, 0x28, 0xba, 0x1a, 0xd2, 0x1e, 0x61, 0x41, 0x8f, 0x84, 0x61, 0x24, 0x89, 0x0c, 0xa2,
	0x50, 0x68, 0x2f, 0xfe, 0x59, 0x80, 0x66, 0x5f, 0xe5, 0xe8, 0x47, 0xa1, 0xe4, 0xc4, 0x97, 0x08,
	0xc1, 0xd2, 0x68, 0x14, 0x0c, 0x6c, 0xab, 0x6d, 0x75, 0xaa, 0xae, 0xfa, 0x8d, 0x56, 0xa1, 0x44,
	0x84, 0xa0, 0xd2, 0x2e, 0x28, 0xa3, 0x7e, 0xa0, 0x75, 0x28, 0x93, 0xeb, 0x68, 0x14, 0x4a, 0xbb,
	0xd8, 0xb6, 0x3a, 0x96, 0x6b, 0x5e, 0x68, 0x1f, 0xee, 0xeb, 0x5f, 0x9e, 0x20, 0xd2, 0xbb, 0x26,
	0xfc, 0x2a, 0x08, 0xed, 0x52, 0xdb, 0xea, 0x14, 0xdd, 0x15, 0xed, 0x38, 0x27, 0xf2, 0x9d, 0x32,
	0xa3, 0x3d, 0x58, 0x99, 0xc1, 0x06, 0x61, 0x20, 0xed, 0xb2, 0x42, 0x36, 0x12, 0xe4, 0x49, 0x18,
	0x48, 0xb4, 0x0b, 0x4d, 0x9d, 0xc8, 0x0b, 0xc2, 0xdb, 0x28, 0xf0, 0xa9, 0xbd, 0xac, 0x5a, 0x69,
	0x68, 0xeb, 0x89, 0x36, 0xa2, 0x6d, 0xa8, 0x4f, 0x72, 0x24, 0xa0, 0x8a, 0x02, 0xd5, 0x26, 0xb6,
	0x18, 0xf2, 0x12, 0x1a, 0xbe, 0x99, 0xd5, 0x93, 0x63, 0x46, 0xed, 0x6a, 0xdb, 0xea, 0x34, 0x0f,
	0x57, 0xbb, 0x43, 0x32, 0xe0, 0xcc, 0xef, 0xc6, 0x44, 0xbc, 0x1f, 0x33, 0xea, 0xd6, 0xfd, 0x99,
	0x17, 0xda, 0x81, 0x86, 0x49, 0x2c, 0x3c, 0x46, 0x82, 0x81, 0x0d, 0x6d, 0xab, 0x53, 0x71, 0xeb,
	0xb1, 0xf1, 0x8c, 0x04, 0x03, 0xfc, 0xd5, 0x82, 0x4d, 0x43, 0x29, 0xa7, 0x44, 0xd2, 0x38, 0x9f,
	0x4b, 0x6f, 0x46, 0x54, 0xc8, 0x29, 0x97, 0x56, 0x3e, 0x97, 0x85, 0x14, 0x97, 0xff, 0x74, 0x5b,
	0xbc, 0x6b, 0xb7, 0xf8, 0x47, 0x01, 0x5a, 0xf9, 0x8d, 0x08, 0x16, 0x85, 0x82, 0xa2, 0x67, 0x50,
	0x89, 0x03, 0x54, 0x33, 0xb5, 0xc3, 0xb5, 0xae, 0x92, 0x50, 0x37, 0x2d, 0x09, 0x37, 0x81, 0xa1,
	0xe7, 0xb0, 0x4e, 0x3f, 0x33, 0xea, 0x4b, 0x3a, 0x30, 0x8b, 0xf5, 0x66, 0xda, 0x2e, 0xba, 0xab,
	0xb1, 0x57, 0xaf, 0xf7, 0x58, 0x0f, 0x71, 0x00, 0x89, 0x5d, 0xad, 0xd8, 0x9b, 0x91, 0x4d, 0xd1,
	0x45, 0xb1, 0x6f, 0xb2, 0x68, 0x13, 0xb1, 0x09, 0xd5, 0x68, 0xc4, 0x3d, 0xc6, 0x27, 0x4b, 0x5c,
	0x52, 0x8c, 0x54, 0xa2, 0x11, 0x3f, 0xe3, 0x66, 0xc9, 0x5a, 0xe2, 0xc6, 0x5f, 0x52, 0xfe, 0x9a,
	0xb6, 0x69, 0xc8, 0x2e, 0x34, 0x19, 0xe5, 0x3e, 0x0d, 0x13, 0xfd, 0x95, 0x15, 0xa8, 0x61, 0xac,
	0xba, 0x3d, 0xdc, 0x83, 0x07, 0x7a, 0xd4, 0x53, 0x46, 0xc3, 0xec, 0xa2, 0x72, 0x0e, 0x01, 0x9f,
	0x82, 0x93, 0x17, 0xf0, 0xdf, 0x84, 0xe2, 0x83, 0x38, 0x61, 0x7f, 0x18, 0x09, 0x7a, 0x97, 0x16,
	0xb6, 0x12, 0x79, 0xa5, 0x23, 0x74, 0x0f, 0xb8, 0x15, 0x27, 0x7c, 0x1b, 0x88, 0xa4, 0xa0, 0x30,
	0x09, 0xb1, 0x1b, 0x07, 0x67, 0xbc, 0x66, 0x80, 0x23, 0xa8, 0xc6, 0x9d, 0x09, 0xdb, 0x6a, 0x17,
	0xe7, 0x4f, 0x30, 0xc5, 0xe1, 0x3e, 0x60, 0xed, 0x34, 0x45, 0xce, 0xc8, 0xf8, 0x7a, 0xfa, 0x8a,
	0x47, 0xd9, 0x02, 0x98, 0x1e, 0xba, 0x1a, 0xa8, 0xe8, 0x56, 0x93, 0x1b, 0xc7, 0xaf, 0x61, 0x67,
	0x61, 0x12, 0xd3, 0xe0, 0x06, 0x2c, 0x33, 0x32, 0xf6, 0x38, 0xbd, 0x31, 0x9c, 0x94, 0x19, 0x19,
	0xbb, 0xf4, 0x06, 0xbf, 0x88, 0x07, 0xcb, 0x8d, 0x9f, 0x1f, 0xf7, 0x30, 0xbe, 0x91, 0x6c, 0x9c,
	0xa1, 0x73, 0x1b, 0x1e, 0x69, 0xff, 0xf9, 0xe8, 0x52, 0xf8, 0x3c, 0xb8, 0xa4, 0x59, 0x4e, 0x0f,
	0x7f, 0x97, 0xa0, 0x76, 0x3c, 0x39, 0x62, 0x0d, 0x44, 0x1f, 0xa0, 0x99, 0x3e, 0x38, 0x84, 0xd3,
	0x1c, 0xe6, 0xfd, 0x59, 0x70, 0x76, 0x16, 0x62, 0xcc, 0xf8, 0xe7, 0x50, 0x9f, 0x15, 0x1e, 0x6a,
	0xa7, 0x82, 0x72, 0x44, 0xec, 0x6c, 0x2f, 0x40, 0x98, 0xa4, 0x17, 0xd0, 0x48, 0x49, 0x09, 0xa5,
	0x63, 0xf2, 0x84, 0xe9, 0xe0, 0x45, 0x10, 0x93, 0xf7, 0x9b, 0x05, 0x6b, 0xf9, 0xdb, 0x78, 0x92,
	0x8a, 0x5e, 0x24, 0x1b, 0x67, 0xff, 0x2e, 0x50, 0xb3, 0x2b, 0xfc, 0xe5, 0xd7, 0x9f, 0xef, 0x85,
	0x16, 0xde, 0xe8, 0x71, 0xed, 0xe9, 0x31, 0x0d, 0x34, 0xcf, 0x57, 0xd6, 0x3e, 0xba, 0x85, 0x66,
	0x3a, 0x49, 0x66, 0x39, 0xb9, 0x15, 0x32, 0xcb, 0x99, 0x23, 0x95, 0x4d, 0x55, 0x7e, 0x0d, 0xdf,
	0xcb, 0x96, 0x9f, 0xd4, 0xbd, 0x80, 0x46, 0xea, 0xe4, 0x32, 0x24, 0xe7, 0x1d, 0x6b, 0x86, 0xe4,
	0xfc, 0x8b, 0xfd, 0x04, 0xf6, 0x54, 0x99, 0xa9, 0x13, 0x15, 0x68, 0x2f, 0x15, 0x3f, 0x57, 0xc0,
	0x4e, 0xfe, 0x89, 0x1f, 0x58, 0x6f, 0x1e, 0x7f, 0xc4, 0x84, 0xfb, 0x24, 0xa4, 0x3e, 0x1f, 0x33,
	0x19, 0xf5, 0x86, 0xa1, 0xfa, 0x67, 0x25, 0x9e, 0xea, 0xcf, 0x8e, 0x9e, 0x0a, 0xbb, 0x2c, 0xab,
	0x4f, 0x89, 0xa3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x81, 0xbb, 0xb8, 0x2f, 0x8d, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AssetClientClient is the client API for AssetClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssetClientClient interface {
	// CreateContract is used to create a contract with the server, but not initiate it yet
	CreateContract(ctx context.Context, in *ClientCreateContractRequest, opts ...grpc.CallOption) (*ClientCreateContractResponse, error)
	// OpenContract is used to initiate a new contract with another host
	OpenContract(ctx context.Context, in *ClientOpenContractRequest, opts ...grpc.CallOption) (*ClientOpenContractResponse, error)
	// CloseContract is used to close a contract with a specific uuid
	CloseContract(ctx context.Context, in *ClientCloseContractRequest, opts ...grpc.CallOption) (*ClientCloseContractResponse, error)
	// RequestPaymentRequest is used to allow another party to create a deposit to us
	RequestPaymentRequest(ctx context.Context, in *ClientRequestPaymentRequestRequest, opts ...grpc.CallOption) (*ClientRequestPaymentRequestResponse, error)
	// RequestPayment is used to allow another party to demand money from us
	RequestPayment(ctx context.Context, in *ClientRequestPaymentRequest, opts ...grpc.CallOption) (*ClientRequestPaymentResponse, error)
	// ListContracts lists all contracts in the database
	ListContracts(ctx context.Context, in *ClientListContractsRequest, opts ...grpc.CallOption) (*ClientListContractsResponse, error)
	// SubscribeContracts returns a stream notified of all new and closed contracts
	SubscribeClientContracts(ctx context.Context, in *ClientSubscribeContractsRequest, opts ...grpc.CallOption) (AssetClient_SubscribeClientContractsClient, error)
}

type assetClientClient struct {
	cc *grpc.ClientConn
}

func NewAssetClientClient(cc *grpc.ClientConn) AssetClientClient {
	return &assetClientClient{cc}
}

func (c *assetClientClient) CreateContract(ctx context.Context, in *ClientCreateContractRequest, opts ...grpc.CallOption) (*ClientCreateContractResponse, error) {
	out := new(ClientCreateContractResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/CreateContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) OpenContract(ctx context.Context, in *ClientOpenContractRequest, opts ...grpc.CallOption) (*ClientOpenContractResponse, error) {
	out := new(ClientOpenContractResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/OpenContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) CloseContract(ctx context.Context, in *ClientCloseContractRequest, opts ...grpc.CallOption) (*ClientCloseContractResponse, error) {
	out := new(ClientCloseContractResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/CloseContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) RequestPaymentRequest(ctx context.Context, in *ClientRequestPaymentRequestRequest, opts ...grpc.CallOption) (*ClientRequestPaymentRequestResponse, error) {
	out := new(ClientRequestPaymentRequestResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/RequestPaymentRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) RequestPayment(ctx context.Context, in *ClientRequestPaymentRequest, opts ...grpc.CallOption) (*ClientRequestPaymentResponse, error) {
	out := new(ClientRequestPaymentResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/RequestPayment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) ListContracts(ctx context.Context, in *ClientListContractsRequest, opts ...grpc.CallOption) (*ClientListContractsResponse, error) {
	out := new(ClientListContractsResponse)
	err := c.cc.Invoke(ctx, "/larpc.AssetClient/ListContracts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetClientClient) SubscribeClientContracts(ctx context.Context, in *ClientSubscribeContractsRequest, opts ...grpc.CallOption) (AssetClient_SubscribeClientContractsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AssetClient_serviceDesc.Streams[0], "/larpc.AssetClient/SubscribeClientContracts", opts...)
	if err != nil {
		return nil, err
	}
	x := &assetClientSubscribeClientContractsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AssetClient_SubscribeClientContractsClient interface {
	Recv() (*ClientContract, error)
	grpc.ClientStream
}

type assetClientSubscribeClientContractsClient struct {
	grpc.ClientStream
}

func (x *assetClientSubscribeClientContractsClient) Recv() (*ClientContract, error) {
	m := new(ClientContract)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AssetClientServer is the server API for AssetClient service.
type AssetClientServer interface {
	// CreateContract is used to create a contract with the server, but not initiate it yet
	CreateContract(context.Context, *ClientCreateContractRequest) (*ClientCreateContractResponse, error)
	// OpenContract is used to initiate a new contract with another host
	OpenContract(context.Context, *ClientOpenContractRequest) (*ClientOpenContractResponse, error)
	// CloseContract is used to close a contract with a specific uuid
	CloseContract(context.Context, *ClientCloseContractRequest) (*ClientCloseContractResponse, error)
	// RequestPaymentRequest is used to allow another party to create a deposit to us
	RequestPaymentRequest(context.Context, *ClientRequestPaymentRequestRequest) (*ClientRequestPaymentRequestResponse, error)
	// RequestPayment is used to allow another party to demand money from us
	RequestPayment(context.Context, *ClientRequestPaymentRequest) (*ClientRequestPaymentResponse, error)
	// ListContracts lists all contracts in the database
	ListContracts(context.Context, *ClientListContractsRequest) (*ClientListContractsResponse, error)
	// SubscribeContracts returns a stream notified of all new and closed contracts
	SubscribeClientContracts(*ClientSubscribeContractsRequest, AssetClient_SubscribeClientContractsServer) error
}

// UnimplementedAssetClientServer can be embedded to have forward compatible implementations.
type UnimplementedAssetClientServer struct {
}

func (*UnimplementedAssetClientServer) CreateContract(ctx context.Context, req *ClientCreateContractRequest) (*ClientCreateContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContract not implemented")
}
func (*UnimplementedAssetClientServer) OpenContract(ctx context.Context, req *ClientOpenContractRequest) (*ClientOpenContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenContract not implemented")
}
func (*UnimplementedAssetClientServer) CloseContract(ctx context.Context, req *ClientCloseContractRequest) (*ClientCloseContractResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseContract not implemented")
}
func (*UnimplementedAssetClientServer) RequestPaymentRequest(ctx context.Context, req *ClientRequestPaymentRequestRequest) (*ClientRequestPaymentRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPaymentRequest not implemented")
}
func (*UnimplementedAssetClientServer) RequestPayment(ctx context.Context, req *ClientRequestPaymentRequest) (*ClientRequestPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPayment not implemented")
}
func (*UnimplementedAssetClientServer) ListContracts(ctx context.Context, req *ClientListContractsRequest) (*ClientListContractsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContracts not implemented")
}
func (*UnimplementedAssetClientServer) SubscribeClientContracts(req *ClientSubscribeContractsRequest, srv AssetClient_SubscribeClientContractsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeClientContracts not implemented")
}

func RegisterAssetClientServer(s *grpc.Server, srv AssetClientServer) {
	s.RegisterService(&_AssetClient_serviceDesc, srv)
}

func _AssetClient_CreateContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientCreateContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).CreateContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/CreateContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).CreateContract(ctx, req.(*ClientCreateContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_OpenContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientOpenContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).OpenContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/OpenContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).OpenContract(ctx, req.(*ClientOpenContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_CloseContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientCloseContractRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).CloseContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/CloseContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).CloseContract(ctx, req.(*ClientCloseContractRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_RequestPaymentRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestPaymentRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).RequestPaymentRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/RequestPaymentRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).RequestPaymentRequest(ctx, req.(*ClientRequestPaymentRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_RequestPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequestPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).RequestPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/RequestPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).RequestPayment(ctx, req.(*ClientRequestPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_ListContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientListContractsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetClientServer).ListContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/larpc.AssetClient/ListContracts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetClientServer).ListContracts(ctx, req.(*ClientListContractsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetClient_SubscribeClientContracts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ClientSubscribeContractsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AssetClientServer).SubscribeClientContracts(m, &assetClientSubscribeClientContractsServer{stream})
}

type AssetClient_SubscribeClientContractsServer interface {
	Send(*ClientContract) error
	grpc.ServerStream
}

type assetClientSubscribeClientContractsServer struct {
	grpc.ServerStream
}

func (x *assetClientSubscribeClientContractsServer) Send(m *ClientContract) error {
	return x.ServerStream.SendMsg(m)
}

var _AssetClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "larpc.AssetClient",
	HandlerType: (*AssetClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContract",
			Handler:    _AssetClient_CreateContract_Handler,
		},
		{
			MethodName: "OpenContract",
			Handler:    _AssetClient_OpenContract_Handler,
		},
		{
			MethodName: "CloseContract",
			Handler:    _AssetClient_CloseContract_Handler,
		},
		{
			MethodName: "RequestPaymentRequest",
			Handler:    _AssetClient_RequestPaymentRequest_Handler,
		},
		{
			MethodName: "RequestPayment",
			Handler:    _AssetClient_RequestPayment_Handler,
		},
		{
			MethodName: "ListContracts",
			Handler:    _AssetClient_ListContracts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeClientContracts",
			Handler:       _AssetClient_SubscribeClientContracts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "client.proto",
}
